services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - app-db:/var/lib/postgresql/data/pgdata
    env_file:
      - postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

volumes:
  app-db:

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: true
