"""add daily table

Revision ID: 0f4758333b46
Revises: 386efa2b984e
Create Date: 2024-05-06 14:05:11.412924

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f4758333b46'
down_revision = '386efa2b984e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockdaily',
    sa.Column('ts_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trade_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_index(op.f('ix_stockdaily_trade_date'), 'stockdaily', ['trade_date'], unique=False)
    op.create_index(op.f('ix_stockdaily_ts_code'), 'stockdaily', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockdaily_ts_code'), table_name='stockdaily')
    op.drop_index(op.f('ix_stockdaily_trade_date'), table_name='stockdaily')
    op.drop_table('stockdaily')
    # ### end Alembic commands ###
