"""alter the stockdaily database structure

Revision ID: 386efa2b984e
Revises: 93862aa4a415
Create Date: 2024-05-06 13:52:05.573484

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '386efa2b984e'
down_revision = '93862aa4a415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stockdaily', 'trade_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_stockdaily_ts_code', table_name='stockdaily')
    op.create_index(op.f('ix_stockdaily_ts_code'), 'stockdaily', ['ts_code'], unique=False)
    op.create_index(op.f('ix_stockdaily_trade_date'), 'stockdaily', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockdaily_trade_date'), table_name='stockdaily')
    op.drop_index(op.f('ix_stockdaily_ts_code'), table_name='stockdaily')
    op.create_index('ix_stockdaily_ts_code', 'stockdaily', ['ts_code'], unique=True)
    op.alter_column('stockdaily', 'trade_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
