"""add stockdaily table

Revision ID: 93862aa4a415
Revises: c5ab54d65889
Create Date: 2024-05-05 17:23:24.749581

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93862aa4a415'
down_revision = 'c5ab54d65889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockdaily',
    sa.Column('ts_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trade_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_index(op.f('ix_stockdaily_ts_code'), 'stockdaily', ['ts_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockdaily_ts_code'), table_name='stockdaily')
    op.drop_table('stockdaily')
    # ### end Alembic commands ###
