"""add new table

Revision ID: c5ab54d65889
Revises: e2412789c190
Create Date: 2024-05-05 15:59:30.769029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5ab54d65889'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockbasic',
    sa.Column('ts_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cnspell', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('curr_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('list_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('list_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delist_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_hs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('act_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('act_ent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ts_code'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockbasic')
    # ### end Alembic commands ###
